version: 2

sources:
  - name: airflow
    schema: public

    tables:
      - name: airflow_demo

        columns:
          - name: id
            data_tests:
              - not_null
              - unique

          - name: name
            data_tests:
              - not_null
